#!/usr/bin/env python3
"""Generate opencl_shim.c: dlopen shim for the vendor OpenCL driver on Android."""
import re, pathlib

NEEDED = """clBuildProgram clCreateBuffer clCreateBufferWithProperties clCreateCommandQueue
clCreateContext clCreateImage clCreateKernel clCreateProgramWithBinary clCreateProgramWithSource
clCreateSubBuffer clEnqueueBarrierWithWaitList clEnqueueCopyBuffer clEnqueueFillBuffer
clEnqueueMarkerWithWaitList clEnqueueNDRangeKernel clEnqueueReadBuffer clEnqueueWriteBuffer
clFinish clFlush clGetDeviceIDs clGetDeviceInfo clGetEventProfilingInfo clGetKernelInfo
clGetKernelSubGroupInfo clGetKernelWorkGroupInfo clGetPlatformIDs clGetPlatformInfo
clGetProgramBuildInfo clGetProgramInfo clReleaseEvent clReleaseKernel clReleaseMemObject
clReleaseProgram clSetKernelArg clWaitForEvents""".split()

HEADER = "/usr/include/CL/cl.h"
OUT = pathlib.Path(__file__).parent / "opencl_shim.c"

text = pathlib.Path(HEADER).read_text()
pat = re.compile(
    r"CL_API_ENTRY\s+(.+?)\s+CL_API_CALL\s+"
    r"(cl[A-Za-z0-9]+)\s*\((.*?)\)\s*"
    r"CL_(?:API|EXT)_SUFFIX__VERSION_[0-9_]+(?:_DEPRECATED)?\s*;",
    re.S)

funcs = {}
for m in pat.finditer(text):
    name = m.group(2)
    if name not in NEEDED:
        continue
    ret = " ".join(m.group(1).split())
    raw = m.group(3).strip()
    params = []
    if raw and raw != "void":
        depth = 0; cur = ""
        for ch in raw:
            if ch == "(": depth += 1
            if ch == ")": depth -= 1
            if ch == "," and depth == 0:
                params.append(cur); cur = ""
            else:
                cur += ch
        params.append(cur)
    typed = []
    for i, p in enumerate(params):
        p = " ".join(p.split())
        if "(" in p:
            p = re.sub(r"\(([^()]*)\)", lambda im: "(" + re.sub(
                r"\*\s*[A-Za-z_][A-Za-z0-9_]*\s*$", f"* p{i}", " ".join(im.group(1).split())) + ")", p, count=1)
            def strip_inner(im):
                parts = []
                for t in im.group(1).split(","):
                    t = " ".join(t.split())
                    if not t: continue
                    toks = t.split()
                    if len(toks) >= 2 and toks[-1] != "*" and re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", toks[-1]):
                        parts.append(" ".join(toks[:-1]))
                    else:
                        parts.append(t)
                return "(" + ", ".join(parts) + ")"
            p = re.sub(r"\(([^()]*)\)\s*$", strip_inner, p, count=1)
            typed.append((p, f"p{i}", True))
            continue
        toks = p.split()
        if len(toks) >= 2 and toks[-1] != "*" and re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", toks[-1]):
            typed.append((" ".join(toks[:-1]), f"p{i}", False))
        else:
            typed.append((p, f"p{i}", False))
    funcs[name] = (ret, typed)

missing = [n for n in NEEDED if n not in funcs]
assert not missing, missing

out = []
out.append("""/* AUTO-GENERATED by gen_opencl_shim.py - do not edit by hand.
 * OpenCL dlopen shim for Android: forwards the CL functions ggml-opencl
 * uses to the vendor driver loaded at runtime, with diagnostics. */
#include <CL/cl.h>
#include <dlfcn.h>
#include <fcntl.h>
#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <stdarg.h>

/* NDK: load from the sphal (vendor public) namespace - the proper way for
 * apps to reach vendor libs like libOpenCL.so. Resolved at runtime. */
typedef void *(*android_load_sphal_library_fn)(const char *, int);
static android_load_sphal_library_fn p_android_load_sphal_library = NULL;
static int g_sphal_resolved = 0;

static void resolve_sphal(void) {
    if (g_sphal_resolved) return;
    g_sphal_resolved = 1;
    p_android_load_sphal_library =
        (android_load_sphal_library_fn)dlsym(RTLD_DEFAULT, "android_load_sphal_library");
    if (!p_android_load_sphal_library) {
        void *h = dlopen("libdl_android.so", RTLD_NOW | RTLD_LOCAL);
        if (!h) h = dlopen("libdl.so", RTLD_NOW | RTLD_LOCAL);
        if (h) p_android_load_sphal_library =
            (android_load_sphal_library_fn)dlsym(h, "android_load_sphal_library");
    }
}

static void *g_cl_lib = NULL;
static char g_diag[4096];
static size_t g_diag_len = 0;

static void diagf(const char *fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    int left = (int)(sizeof(g_diag) - g_diag_len - 1);
    if (left > 0) {
        int n = vsnprintf(g_diag + g_diag_len, left, fmt, ap);
        if (n > 0) g_diag_len += (size_t)(n > left ? left : n);
    }
    va_end(ap);
}
""")
for name, (ret, typed) in funcs.items():
    ptr_types = ", ".join(t for t, _, _ in typed) if typed else "void"
    out.append(f"static {ret} (CL_API_CALL *p_{name})({ptr_types});\n")
out.append("""
__attribute__((constructor)) static void opencl_shim_init(void) {
    static const char *cands[] = {
        "libOpenCL.so", "/vendor/lib64/libOpenCL.so",
        "/system/vendor/lib64/libOpenCL.so", "/system/lib64/libOpenCL.so",
        "libOpenCL.so.1", NULL };
    diagf("opencl shim init\\n");
    resolve_sphal();
    diagf("android_load_sphal_library: %s\\n",
          p_android_load_sphal_library ? "available" : "not found");
    int kgsl = open("/dev/kgsl-3d0", O_RDWR);
    diagf("/dev/kgsl-3d0 O_RDWR: %s\\n", kgsl >= 0 ? "ok" : "failed");
    if (kgsl >= 0) close(kgsl);
    int rdri = open("/dev/dri/renderD128", O_RDWR);
    diagf("/dev/dri/renderD128 O_RDWR: %s\\n", rdri >= 0 ? "ok" : "failed");
    if (rdri >= 0) close(rdri);
    for (int i = 0; cands[i]; i++) {
        void *h = NULL;
        const char *err = NULL;
        if (p_android_load_sphal_library) {
            h = p_android_load_sphal_library(cands[i], RTLD_NOW | RTLD_LOCAL);
            if (!h) err = dlerror();
            diagf("sphal %s: %s%s\\n", cands[i], h ? "ok" : "failed", h ? "" : (err ? err : ""));
        }
        if (!h) {
            h = dlopen(cands[i], RTLD_NOW | RTLD_LOCAL);
            if (!h) err = dlerror();
            diagf("dlopen %s: %s%s\\n", cands[i], h ? "ok" : "failed", h ? "" : (err ? err : ""));
        }
        if (!h) continue;
        int missing_syms = 0;
""")
for name in funcs:
    out.append(f'        p_{name} = dlsym(h, "{name}"); if (!p_{name}) {{ diagf("  missing: {name}\\n"); missing_syms++; }}\n')
out.append("""        if (missing_syms == 0) { g_cl_lib = h; diagf("driver loaded from %s\\n", cands[i]); break; }
        g_cl_lib = NULL;
    }
    if (g_cl_lib) {
        unsigned int nplat = 0;
        cl_int err = p_clGetPlatformIDs(0, NULL, &nplat);
        diagf("clGetPlatformIDs probe: err=%d platforms=%u\\n", (int)err, nplat);
    } else {
        diagf("no driver loaded -> clGetPlatformIDs returns -1001\\n");
    }
}

int opencl_shim_available(void) { return g_cl_lib != NULL; }

const char *opencl_shim_debug(void) { return g_diag; }
""")
for name, (ret, typed) in funcs.items():
    decl = ", ".join((t if emb else f"{t} {n}") for t, n, emb in typed) if typed else "void"
    call = ", ".join(n for _, n, _ in typed)
    body = f"    if (!p_{name}) return ({ret})0;\n    return p_{name}({call});\n"
    if name == "clGetPlatformIDs":
        body = "    if (!g_cl_lib || !p_clGetPlatformIDs) return -1001;\n    return p_clGetPlatformIDs(%s);\n" % call
    out.append(f"CL_API_ENTRY {ret} CL_API_CALL {name}({decl}) {{\n{body}}}\n\n")

OUT.write_text("".join(out))
print(f"generated {OUT} ({len(funcs)} functions)")
